language: node_js
node_js:
  - "node"
  - "8"

notifications:
  slack:
    on_success: change
    on_failure: always
  email:
    recipients:
      - sam.he@cargosmart.com
    on_success: change # default: change
    on_failure: always # default: always

cache:
  directories:
    - node_modules

addons:
  sonarcloud:
    organization: "samhe-github" # the key of the org you chose at step #3
script:
  - yarn install && npm run test
  - sonar-scanner
