language: node_js
node_js:
  - "node"
  - "8"

notifications:
  slack:
    on_success: change
    on_failure: always
  email:
    recipients:
      - sam.he@cargosmart.com
    on_success: change # default: change
    on_failure: always # default: always

cache: yarn
  yarn: true
  directories:
    - node_modules
